plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    namespace 'com.stark.flutter_kronos'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 21
        targetSdk 36
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    compileSdk 36
    buildToolsVersion '35.0.0'
}

dependencies {
    implementation "com.lyft.kronos:kronos-android:0.0.1-alpha11"
}
